
name: Testing
on: 
  push:
    branches:
      - main

jobs:
  toPDF:
    name: Testing Bottom Penguin
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            rsa
      - run: |
          python bottom/setup.py install
          python test/test.py